/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardImport } from './routes/_dashboard'
import { Route as DashboardUsersImport } from './routes/_dashboard/users'
import { Route as DashboardMeImport } from './routes/_dashboard/me'
import { Route as DashboardHoursTableImport } from './routes/_dashboard/hoursTable'
import { Route as DashboardCalendarImport } from './routes/_dashboard/calendar'
import { Route as DashboardAssignUserToManagerImport } from './routes/_dashboard/assignUserToManager'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const DashboardUsersRoute = DashboardUsersImport.update({
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardMeRoute = DashboardMeImport.update({
  path: '/me',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardHoursTableRoute = DashboardHoursTableImport.update({
  path: '/hoursTable',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardCalendarRoute = DashboardCalendarImport.update({
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardAssignUserToManagerRoute =
  DashboardAssignUserToManagerImport.update({
    path: '/assignUserToManager',
    getParentRoute: () => DashboardRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/assignUserToManager': {
      preLoaderRoute: typeof DashboardAssignUserToManagerImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/calendar': {
      preLoaderRoute: typeof DashboardCalendarImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/hoursTable': {
      preLoaderRoute: typeof DashboardHoursTableImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/me': {
      preLoaderRoute: typeof DashboardMeImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/users': {
      preLoaderRoute: typeof DashboardUsersImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  DashboardRoute.addChildren([
    DashboardAssignUserToManagerRoute,
    DashboardCalendarRoute,
    DashboardHoursTableRoute,
    DashboardMeRoute,
    DashboardUsersRoute,
  ]),
  LoginRoute,
])

/* prettier-ignore-end */
